// Themenpakete: kuratierte Songlisten (Interpret, Titel, Jahr). Hörproben und Cover holt
// die App einzeln über die iTunes-Suche; das Jahr aus der Liste gilt, weil iTunes bei
// Neuauflagen und Compilations oft ein späteres Jahr meldet.
import { searchSongs, normalize } from './api.js';
import { textMatches } from './questions.js';

export const PACKS = [
  {
    id: 'hits90',
    name: 'Hits der 90er',
    icon: '📼',
    desc: 'Bekannte Hits 1990–1999, deutsch und international: Pop, Eurodance, Rock, Hip-Hop.',
    songs: [
      // 1990
      ["Sinéad O'Connor", 'Nothing Compares 2 U', 1990],
      ['MC Hammer', "U Can't Touch This", 1990],
      ['Snap!', 'The Power', 1990],
      ['Madonna', 'Vogue', 1990],
      ['Vanilla Ice', 'Ice Ice Baby', 1990],
      ['Roxette', 'It Must Have Been Love', 1990],
      ['Scorpions', 'Wind of Change', 1990],
      ['Deee-Lite', 'Groove Is in the Heart', 1990],
      ['Matthias Reim', "Verdammt, ich lieb' dich", 1990],
      ['Wilson Phillips', 'Hold On', 1990],
      ['Enigma', 'Sadeness', 1990],
      ['Mariah Carey', 'Vision of Love', 1990],
      ['Cher', 'The Shoop Shoop Song', 1990],
      ['Londonbeat', "I've Been Thinking About You", 1990],
      // 1991
      ['Bryan Adams', '(Everything I Do) I Do It for You', 1991],
      ['R.E.M.', 'Losing My Religion', 1991],
      ['Nirvana', 'Smells Like Teen Spirit', 1991],
      ['Queen', 'The Show Must Go On', 1991],
      ['Queen', 'Innuendo', 1991],
      ['Michael Jackson', 'Black or White', 1991],
      ['Metallica', 'Nothing Else Matters', 1991],
      ['Color Me Badd', 'I Wanna Sex You Up', 1991],
      ['Marky Mark and the Funky Bunch', 'Good Vibrations', 1991],
      ['Salt-N-Pepa', "Let's Talk About Sex", 1991],
      ['Massive Attack', 'Unfinished Sympathy', 1991],
      ['Roxette', 'Joyride', 1991],
      ['Rozalla', "Everybody's Free", 1991],
      ['Crystal Waters', 'Gypsy Woman', 1991],
      ['2 Unlimited', 'Get Ready for This', 1991],
      ['Simply Red', 'Stars', 1991],
      ['Extreme', 'More Than Words', 1991],
      ['Genesis', "I Can't Dance", 1991],
      ['Right Said Fred', "I'm Too Sexy", 1991],
      ['Mr. Big', 'To Be With You', 1991],
      ['Die Prinzen', 'Millionär', 1991],
      ['The KLF', '3 a.m. Eternal', 1991],
      // 1992
      ['Whitney Houston', 'I Will Always Love You', 1992],
      ['Snap!', 'Rhythm Is a Dancer', 1992],
      ['Dr. Alban', "It's My Life", 1992],
      ['Dr. Alban', 'Sing Hallelujah', 1992],
      ['Kris Kross', 'Jump', 1992],
      ['Sir Mix-a-Lot', 'Baby Got Back', 1992],
      ['Boyz II Men', 'End of the Road', 1992],
      ["Shakespears Sister", 'Stay', 1992],
      ['Charles & Eddie', 'Would I Lie to You?', 1992],
      ['Annie Lennox', 'Why', 1992],
      ['Eric Clapton', 'Tears in Heaven', 1992],
      ['Red Hot Chili Peppers', 'Under the Bridge', 1992],
      ['Snow', 'Informer', 1992],
      ['Billy Ray Cyrus', 'Achy Breaky Heart', 1992],
      ['En Vogue', 'My Lovin\'', 1992],
      ['Die Prinzen', 'Küssen verboten', 1992],
      ['Die Fantastischen Vier', 'Die da!?!', 1992],
      ['Captain Hollywood Project', 'More and More', 1992],
      ['Ace of Base', 'All That She Wants', 1992],
      ['Inner Circle', 'Sweat (A La La La La Long)', 1992],
      ['Jon Secada', 'Just Another Day', 1992],
      ['Nirvana', 'Come as You Are', 1992],
      ['Radiohead', 'Creep', 1992],
      ['Guns N\' Roses', 'November Rain', 1992],
      ['U2', 'One', 1992],
      ['DJ BoBo', 'Somebody Dance with Me', 1992],
      // 1993
      ['Culture Beat', 'Mr. Vain', 1993],
      ['Haddaway', 'What Is Love', 1993],
      ['4 Non Blondes', "What's Up?", 1993],
      ['UB40', "(I Can't Help) Falling in Love with You", 1993],
      ['Ace of Base', 'The Sign', 1993],
      ['Meat Loaf', "I'd Do Anything for Love (But I Won't Do That)", 1993],
      ['Aerosmith', "Cryin'", 1993],
      ['Tina Turner', "I Don't Wanna Fight", 1993],
      ['Take That', 'Pray', 1993],
      ['Real McCoy', 'Another Night', 1993],
      ['Twenty 4 Seven', 'Slave to the Music', 1993],
      ['Jam & Spoon', 'Right in the Night', 1993],
      ['2 Unlimited', 'No Limit', 1993],
      ['Cappella', 'U Got 2 Let the Music', 1993],
      ['Urban Cookie Collective', 'The Key the Secret', 1993],
      ['Chaka Demus & Pliers', 'Tease Me', 1993],
      ['Shaggy', 'Oh Carolina', 1993],
      ['Pet Shop Boys', 'Go West', 1993],
      ['Gabrielle', 'Dreams', 1993],
      ['Crash Test Dummies', 'Mmm Mmm Mmm Mmm', 1993],
      ['Lenny Kravitz', 'Are You Gonna Go My Way', 1993],
      ['Mariah Carey', 'Hero', 1993],
      ['Bryan Adams', 'Please Forgive Me', 1993],
      ['Die Ärzte', 'Schrei nach Liebe', 1993],
      ['Die Prinzen', 'Alles nur geklaut', 1993],
      // 1994
      ['Scatman John', "Scatman (Ski-Ba-Bop-Ba-Dop-Bop)", 1994],
      ['Corona', 'The Rhythm of the Night', 1994],
      ['Whigfield', 'Saturday Night', 1994],
      ['Rednex', 'Cotton Eye Joe', 1994],
      ['Ini Kamoze', 'Here Comes the Hotstepper', 1994],
      ['Masterboy', 'Feel the Heat of the Night', 1994],
      ['Pharao', 'There Is a Star', 1994],
      ['E-Rotic', "Max Don't Have Sex with Your Ex", 1994],
      ['Ice MC', 'Think About the Way', 1994],
      ['Marusha', 'Over the Rainbow', 1994],
      ["Mark 'Oh", "Tears Don't Lie", 1994],
      ['Scooter', 'Hyper Hyper', 1994],
      ['Mo-Do', 'Eins, Zwei, Polizei', 1994],
      ['DJ BoBo', 'Everybody', 1994],
      ['Lucilectric', 'Mädchen', 1994],
      ['Wet Wet Wet', 'Love Is All Around', 1994],
      ['Mariah Carey', 'Without You', 1994],
      ['Mariah Carey', 'All I Want for Christmas Is You', 1994],
      ['Bon Jovi', 'Always', 1994],
      ['Prince', 'The Most Beautiful Girl in the World', 1994],
      ['The Cranberries', 'Zombie', 1994],
      ['Green Day', 'Basket Case', 1994],
      ['Sheryl Crow', 'All I Wanna Do', 1994],
      ['Seal', 'Kiss from a Rose', 1994],
      ["Des'ree", 'You Gotta Be', 1994],
      ['East 17', 'Stay Another Day', 1994],
      ['Warren G & Nate Dogg', 'Regulate', 1994],
      ['The Notorious B.I.G.', 'Juicy', 1994],
      // 1995
      ['Coolio', "Gangsta's Paradise", 1995],
      ['Michael Jackson', 'Earth Song', 1995],
      ['Michael Jackson', 'You Are Not Alone', 1995],
      ['Oasis', 'Wonderwall', 1995],
      ['Alanis Morissette', 'You Oughta Know', 1995],
      ['Shaggy', 'Boombastic', 1995],
      ['Scooter', 'Move Your Ass!', 1995],
      ['Dune', 'Hardcore Vibes', 1995],
      ["Fool's Garden", 'Lemon Tree', 1995],
      ['Los Del Rio', 'Macarena', 1995],
      ['Robert Miles', 'Children', 1995],
      ['Take That', 'Back for Good', 1995],
      ['La Bouche', 'Be My Lover', 1995],
      ['Sin with Sebastian', 'Shut Up (And Sleep with Me)', 1995],
      ['Captain Jack', 'Captain Jack', 1995],
      ['Blümchen', 'Herz an Herz', 1995],
      ['Pur', 'Abenteuerland', 1995],
      ['Fettes Brot', 'Nordisch by Nature', 1995],
      ['Die Fantastischen Vier', 'Sie ist weg', 1995],
      ['TLC', 'Waterfalls', 1995],
      ['Mariah Carey', 'Fantasy', 1995],
      ['Mariah Carey & Boyz II Men', 'One Sweet Day', 1995],
      ['Pulp', 'Common People', 1995],
      ['Faithless', 'Insomnia', 1995],
      ['2Pac', 'California Love', 1995],
      // 1996
      ['Fugees', 'Killing Me Softly with His Song', 1996],
      ['Spice Girls', 'Wannabe', 1996],
      ['Andrea Bocelli & Sarah Brightman', 'Time to Say Goodbye', 1996],
      ['Mark Morrison', 'Return of the Mack', 1996],
      ['Toni Braxton', 'Un-Break My Heart', 1996],
      ['No Doubt', "Don't Speak", 1996],
      ['Mr. President', 'Coco Jamboo', 1996],
      ['Gala', 'Freed from Desire', 1996],
      ['No Mercy', 'Where Do You Go', 1996],
      ['The Prodigy', 'Firestarter', 1996],
      ['The Prodigy', 'Breathe', 1996],
      ['Underworld', 'Born Slippy', 1996],
      ['Oasis', "Don't Look Back in Anger", 1996],
      ['Alanis Morissette', 'Ironic', 1996],
      ['The Cardigans', 'Lovefool', 1996],
      ['George Michael', 'Fastlove', 1996],
      ['R. Kelly', 'I Believe I Can Fly', 1996],
      ['Backstreet Boys', "Quit Playing Games (With My Heart)", 1996],
      ['Fettes Brot', 'Jein', 1996],
      ['Tic Tac Toe', 'Ich find dich scheiße', 1996],
      ['Die Toten Hosen', 'Zehn kleine Jägermeister', 1996],
      // 1997
      ['Puff Daddy & Faith Evans', "I'll Be Missing You", 1997],
      ['Aqua', 'Barbie Girl', 1997],
      ['Hanson', 'MMMBop', 1997],
      ['Chumbawamba', 'Tubthumping', 1997],
      ['The Verve', 'Bitter Sweet Symphony', 1997],
      ['Elton John', 'Candle in the Wind 1997', 1997],
      ['Celine Dion', 'My Heart Will Go On', 1997],
      ['Backstreet Boys', 'Everybody (Backstreet\'s Back)', 1997],
      ['Natalie Imbruglia', 'Torn', 1997],
      ['All Saints', 'Never Ever', 1997],
      ['Robbie Williams', 'Angels', 1997],
      ['Blur', 'Song 2', 1997],
      ['Daft Punk', 'Around the World', 1997],
      ['Eros Ramazzotti & Tina Turner', 'Cose della vita', 1997],
      ['Run-DMC & Jason Nevins', "It's Like That", 1997],
      ['Eagle-Eye Cherry', 'Save Tonight', 1997],
      ['Will Smith', 'Men in Black', 1997],
      ['Savage Garden', 'Truly Madly Deeply', 1997],
      ['Spice Girls', 'Spice Up Your Life', 1997],
      ['Sash!', 'Ecuador', 1997],
      ['Nana', 'Lonely', 1997],
      ['Wes', 'Alane', 1997],
      ['Rammstein', 'Du hast', 1997],
      ['Rammstein', 'Engel', 1997],
      ['Tic Tac Toe', 'Warum?', 1997],
      ['Sabrina Setlur', 'Du liebst mich nicht', 1997],
      ['Lighthouse Family', 'High', 1997],
      ['Meredith Brooks', 'Bitch', 1997],
      ['Third Eye Blind', 'Semi-Charmed Life', 1997],
      ['The Notorious B.I.G.', 'Hypnotize', 1997],
      // 1998
      ['Cher', 'Believe', 1998],
      ['Britney Spears', '...Baby One More Time', 1998],
      ['Madonna', 'Frozen', 1998],
      ['Aerosmith', "I Don't Want to Miss a Thing", 1998],
      ['Goo Goo Dolls', 'Iris', 1998],
      ['Shania Twain', "You're Still the One", 1998],
      ['Shania Twain', "That Don't Impress Me Much", 1998],
      ['Brandy & Monica', 'The Boy Is Mine', 1998],
      ['Lauryn Hill', 'Doo Wop (That Thing)', 1998],
      ['Will Smith', "Gettin' Jiggy wit It", 1998],
      ['The Offspring', 'Pretty Fly (For a White Guy)', 1998],
      ['Fatboy Slim', 'Praise You', 1998],
      ['Fatboy Slim', 'The Rockafeller Skank', 1998],
      ['ATB', '9 PM (Till I Come)', 1998],
      ['Mousse T. & Hot \'n\' Juicy', "Horny '98", 1998],
      ['Vengaboys', 'Boom, Boom, Boom, Boom!!', 1998],
      ['Loona', 'Bailando', 1998],
      ['Robbie Williams', 'Millennium', 1998],
      ['Lenny Kravitz', 'Fly Away', 1998],
      ['Sasha', 'If You Believe', 1998],
      ['Oli. P', 'Flugzeuge im Bauch', 1998],
      ['Guildo Horn', 'Guildo hat euch lieb!', 1998],
      ['Die Ärzte', 'Männer sind Schweine', 1998],
      ['2Pac', 'Changes', 1998],
      // 1999
      ['Lou Bega', 'Mambo No. 5', 1999],
      ['Ricky Martin', "Livin' la Vida Loca", 1999],
      ['Santana', 'Smooth', 1999],
      ['Eiffel 65', 'Blue (Da Ba Dee)', 1999],
      ['Vengaboys', "We're Going to Ibiza!", 1999],
      ['Backstreet Boys', 'I Want It That Way', 1999],
      ['Britney Spears', 'Sometimes', 1999],
      ['Christina Aguilera', 'Genie in a Bottle', 1999],
      ['Jennifer Lopez', 'If You Had My Love', 1999],
      ['Enrique Iglesias', 'Bailamos', 1999],
      ['TLC', 'No Scrubs', 1999],
      ['Moby', 'Why Does My Heart Feel So Bad?', 1999],
      ['Eminem', 'My Name Is', 1999],
      ['Dr. Dre & Snoop Dogg', 'Still D.R.E.', 1999],
      ['Smash Mouth', 'All Star', 1999],
      ['Sugar Ray', 'Every Morning', 1999],
      ['Bloodhound Gang', 'The Bad Touch', 1999],
      ['Bomfunk MC\'s', 'Freestyler', 1999],
      ['Echt', 'Du trägst keine Liebe in dir', 1999],
    ],
  },
];

export const packKey = (artist, title) => normalize(artist) + '|' + normalize(title);

// Gleicher Interpret? Kollaborationen („A & B“, „feat.“) zählen, wenn der Hauptname passt.
function sameArtist(listed, found) {
  const a = normalize(listed), b = normalize(found);
  const main = a.split(/ und | x | vs /)[0];
  return b.includes(main) || a.includes(b) || textMatches(found, listed);
}

// Sucht einen Song der Liste bei iTunes; null, wenn kein passender Treffer mit Hörprobe.
export async function lookupPackSong([artist, title, year], { country }) {
  const found = await searchSongs(`${artist} ${title}`, { attr: 'all', limit: 15, country, originalsOnly: true });
  const match = found.find(s => textMatches(s.t, title) && sameArtist(artist, s.a))
    || found.find(s => textMatches(title, s.t) && sameArtist(artist, s.a));
  if (!match) return null;
  return { ...match, y: year, pk: packKey(artist, title) };
}
